### ISSUE TITLE
Catherine tasks

### ISSUE THREAD

**Issue by TobMcG** [geog575-spring2016/economic-geographer-575#5]
upload/download for user's own data w/ template spreadsheet
overlay point data

**Comment by TobMcG** [comment]
migration csv

**Comment by TobMcG** [comment]
jsut put a dash ('-')  for no data

**Comment by catherinestreiffer** [comment]
added 51515,-,-,-,- line to migration csv
added branch for upload/download for user's own data w/template spreadsheet

**Comment by catherinestreiffer** [comment]
don't merge the branch yet - I need to add the fileReader

**Comment by catherinestreiffer** [comment]
branch works to upload data and use in scatterplot. Will next fix bug that is making choropleth highlighting not work because it is expecting an uploaded file to always be there on first load of the map.

**Comment by TobMcG** [comment]
for thursday merge branch (copy/paste to master), change upload to load in y axis, choropleth doesnt crash without data uploaded. Link uploaded data in map display.

**Comment by catherinestreiffer** [comment]
merge branch - done. 
change upload to load in y axis - done
choropleth doesn't crash - turns out it was Schuyler's bug, not mine
next will link uploaded data in map display.

**Comment by catherinestreiffer** [comment]
uploaded data works in map display now that it's in d3.
